# Site settings
title: "Ari Barkhah Resume"
description: "A professional resume of Ari Mohamad Barkhah"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ari Barkhah"
resume_title:                   "Product Manager & Jr. Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ari.barkhah@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+62 812 9688 8998"
resume_contact_address:         "Jakarta, Indonesia"

resume_header_contact_info:     "Jakarta, Indonesia • +62 812 9688 8998 • ari.barkhah@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p align=justify>As a <b>product manager</b>, I have led more than <b>six challenging products</b>.
  My experience includes in <b>e-procurement</b>, <b>e-marketplace</b>, and <b>e-commerce</b> area.
  Apart from that, as a <b>data analyst</b>, I have <b>queried</b>, <b>analyzed</b>, and <b>visualized</b> data for six years to <b>evaluate</b> and <b>improve</b> the quality of existing <b>products</b>.
  Moreover, I have been <b>modeling</b> and <b>predicting</b> projects since I took my master's.
  I am looking for <b>opportunities</b> to <b>help</b> a tech <b>company</b> <b>reach</b> its <b>goals</b> and <b>deepen my skills</b> while working as a <b>product manager</b> or <b>data scientist</b>.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_associations:    false
resume_section_links:           false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_linkedin_url: "https://www.linkedin.com/in/aribarkhah"
  resume_github_url:            "https://github.com/arymbe"
  resume_medium_url: "https://medium.com/@arymbe"
  resume_twitter_url:           "http://twitter.com/arymbe"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_instagram_url:         "https://www.instagram.com/arymbe/"
  resume_website_url:           "https://arymbe.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
